services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: vatsim_postgres
    environment:
      POSTGRES_DB: vatsim_data
      POSTGRES_USER: vatsim_user
      POSTGRES_PASSWORD: vatsim_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    #check postgres is up before allowing app to connect
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vatsim_user -d vatsim_data"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Main Application (API-First Architecture)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vatsim_app
    environment:
      # Database Configuration
      DATABASE_URL: postgresql://vatsim_user:vatsim_password@postgres:5432/vatsim_data
      
      # Simplified Architecture - Sprint 2 Completed
      LOG_LEVEL: "INFO"
      
      # Production Settings
      PRODUCTION_MODE: "true"
      
      # Performance Settings
      MEMORY_LIMIT_MB: 2048
      BATCH_SIZE_THRESHOLD: 10000
      
      # VATSIM Data Collection Intervals (seconds)
      VATSIM_POLLING_INTERVAL: 60    # How often to fetch VATSIM data (60 seconds)

      WRITE_TO_DISK_INTERVAL: 30    # How often to write data to disk (2 minutes)
      VATSIM_API_TIMEOUT: 60         # VATSIM API timeout in seconds
      VATSIM_API_RETRY_ATTEMPTS: 20   # Number of retry attempts for VATSIM API
      
      # Cache Optimization
      CACHE_MAX_SIZE: 50000          # Increase cache capacity
      
      # Optional: More aggressive caching for static data

      
      # Database Configuration
      DATABASE_POOL_SIZE: 20         # Database connection pool size (optimized)
      DATABASE_MAX_OVERFLOW: 40      # Database max overflow connections (optimized)
      DATABASE_POOL_TIMEOUT: 10      # Database pool timeout in seconds (optimized)
      DATABASE_ECHO: "false"         # Enable SQL echo for debugging
      
      # API Configuration
      API_WORKERS: 4                 # Number of API workers
      API_DEBUG: "false"             # Enable API debug mode
      API_RELOAD: "false"            # Enable API auto-reload
      CORS_ORIGINS: "*"              # CORS allowed origins
      
      # Simplified Service Architecture
      # Over-engineered service management removed - direct service initialization
      
      # Logging Configuration
      LOG_FORMAT: "json"
      LOG_MAX_FILE_SIZE: 10485760    # 10MB in bytes
      LOG_BACKUP_COUNT: 5
      

      
      # Geographic Boundary Filter Configuration (Polygon-based)
      ENABLE_BOUNDARY_FILTER: "true"
      BOUNDARY_DATA_PATH: "config/australian_airspace_polygon.json"
      BOUNDARY_FILTER_LOG_LEVEL: "INFO"
      BOUNDARY_FILTER_PERFORMANCE_THRESHOLD: "10.0"
      
      # Callsign Pattern Filter Configuration
      EXCLUDED_CALLSIGN_PATTERNS: "ATIS"
      
      # Flight Summary System Configuration
      FLIGHT_SUMMARY_ENABLED: "true"          # Enable flight summary processing
      FLIGHT_COMPLETION_HOURS: 14              # Hours after logon to mark flight as complete
      FLIGHT_RETENTION_HOURS: 168             # Hours to keep detailed flight data (7 days)
      FLIGHT_SUMMARY_INTERVAL: 60              # Minutes between summary processing (1 hour)
      SECTOR_TRACKING_ENABLED: "true"         # Enable real-time sector occupancy tracking
      SECTOR_UPDATE_INTERVAL: 60              # Seconds between sector position updates (1 minute)
      SECTOR_OFFLINE_THRESHOLD_MINUTES: 2     # Minutes offline before forcing sector exit




    volumes:
      - ./logs:/app/logs:rw
      - ./config/australian_airspace_polygon.json:/app/airspace_sector_data/australian_airspace_polygon.json:ro
      - ./config/australian_airspace_sectors.geojson:/app/airspace_sector_data/australian_airspace_sectors.geojson:ro
      - ./config/init.sql:/app/database/init.sql:ro
      # REMOVE FOR PRODUCTION - Test and debug files
      - ./pytest.ini:/app/pytest.ini:ro
      - ./tests:/app/tests:ro
    ports:
      - "8001:8001"
      #wait for postgres to be ready
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped




  # Metabase for business intelligence and analytics
  metabase:
    image: metabase/metabase:latest
    container_name: vatsim_metabase
    environment:
      # Metabase will use the existing vatsim_data database
      # No separate database needed - Metabase stores its config in the app container
      
      # Metabase configuration
      MB_ENCRYPTION_SECRET_KEY: "your-secret-key-here-change-in-production"
      MB_PASSWORD_COMPLEXITY: "strong"
      MB_PASSWORD_LENGTH: 10
      
      # Performance settings
      MB_JAVA_TIMEZONE: UTC
      MB_MAX_MEMORY_PERCENTAGE: 75
      
      # Security settings
      MB_SESSION_TIMEOUT: 20160  # 14 days in minutes
      MB_SESSION_TIMEOUT_UNITS: minutes
      
    volumes:
      - metabase_data:/metabase-data
    ports:
      - "3030:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s


 

# Define named volumes
volumes:
  postgres_data:
    driver: local
  metabase_data:
    driver: local 