services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: vatsim_postgres
    environment:
      POSTGRES_DB: vatsim_data
      POSTGRES_USER: vatsim_user
      POSTGRES_PASSWORD: vatsim_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tools/postgresql_write_optimized.conf:/etc/postgresql/postgresql.conf
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vatsim_user -d vatsim_data"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: vatsim_redis
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --save 30 1
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Main Application (API-First Architecture)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vatsim_app
    environment:
      # Database and Cache
      DATABASE_URL: postgresql://vatsim_user:vatsim_password@postgres:5432/vatsim_data
      REDIS_URL: redis://redis:6379
      
      # API Configuration
      API_HOST: 0.0.0.0
      API_PORT: 8001
      PYTHONUNBUFFERED: 1
      
      # Centralized Error Handling
      ERROR_MONITORING_ENABLED: "true"
      LOG_LEVEL: "INFO"
      
      # Production Settings
      PRODUCTION_MODE: "true"
      
      # Performance Settings
      MEMORY_LIMIT_MB: 2048
      BATCH_SIZE_THRESHOLD: 10000
      
      # VATSIM Data Collection Intervals (seconds)
      VATSIM_POLLING_INTERVAL: 30    # How often to fetch VATSIM data (10 seconds)

      WRITE_TO_DISK_INTERVAL: 60     # How often to write data to disk (15 seconds)
      VATSIM_API_TIMEOUT: 60         # VATSIM API timeout in seconds
      VATSIM_API_RETRY_ATTEMPTS: 20   # Number of retry attempts for VATSIM API

      
      # Database Configuration
      DATABASE_POOL_SIZE: 10         # Database connection pool size
      DATABASE_MAX_OVERFLOW: 20      # Database max overflow connections
      DATABASE_ECHO: "false"         # Enable SQL echo for debugging
      
      # API Configuration
      API_WORKERS: 4                 # Number of API workers
      API_DEBUG: "false"             # Enable API debug mode
      API_RELOAD: "false"            # Enable API auto-reload
      CORS_ORIGINS: "*"              # CORS allowed origins
      

      

      
      # Logging Configuration
      LOG_FORMAT: "json"
      LOG_MAX_FILE_SIZE: 10485760    # 10MB in bytes
      LOG_BACKUP_COUNT: 5
      

      
      # Flight Filter Configuration (Airport-based)
      FLIGHT_FILTER_ENABLED: "true"
      FLIGHT_FILTER_LOG_LEVEL: "INFO"
      
      # Geographic Boundary Filter Configuration (Polygon-based)
      ENABLE_BOUNDARY_FILTER: "true"
      BOUNDARY_DATA_PATH: "australian_airspace_polygon.json"
      BOUNDARY_FILTER_LOG_LEVEL: "INFO"
      BOUNDARY_FILTER_PERFORMANCE_THRESHOLD: "10.0"
      




    volumes:
      - ./logs:/app/logs:rw
      - ./australian_airspace_polygon.json:/app/australian_airspace_polygon.json:ro
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vatsim-api.rule=Host(`api.vatsim.local`)"
      - "traefik.http.services.vatsim-api.loadbalancer.server.port=8001"

  # Grafana for data visualization and monitoring
  grafana:
    image: grafana/grafana:10.2.0
    container_name: vatsim_grafana
    user: "1000:1000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_OAUTH_AUTO_LOGIN: true
      GF_AUTH_BASIC_ENABLED: false
      GF_AUTH_ANONYMOUS_ORG_NAME: Main Org.
      GF_DEFAULT_LOCALE: en-GB
      GF_USERS_DEFAULT_THEME: dark
      # Set to UTC to ensure dashboard displays database timestamps as UTC times
      # Database stores all timestamps in UTC, this prevents timezone conversion
      GF_USERS_DEFAULT_TIMEZONE: UTC
      # Error monitoring and observability
      GF_FEATURE_TOGGLES_ENABLE: "publicDashboards"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    ports:
      - "3050:3000"
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vatsim-grafana.rule=Host(`grafana.vatsim.local`)"
      - "traefik.http.services.vatsim-grafana.loadbalancer.server.port=3000"

# Optional: Traefik reverse proxy for production
# Uncomment to enable reverse proxy with SSL termination
# traefik:
#   image: traefik:v2.10
#   container_name: vatsim_traefik
#   command:
#     - "--api.insecure=true"
#     - "--providers.docker=true"
#     - "--providers.docker.exposedbydefault=false"
#     - "--entrypoints.web.address=:80"
#     - "--entrypoints.websecure.address=:443"
#   ports:
#     - "80:80"
#     - "443:443"
#     - "8080:8080"
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock:ro
#   restart: unless-stopped 

# Define named volumes
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local 