apiVersion: 1

datasources:
  - name: vatsim_health_api
    type: grafana-simple-json-datasource
    uid: vatsim_health_api
    url: http://app:8001
    jsonData:
      httpMethod: GET
      defaultQuery: |
        {
          "targets": [
            {
              "target": "overall_health",
              "refId": "A"
            }
          ]
        }
      customQueryParams: |
        {
          "endpoint": "/api/health/comprehensive",
          "timeout": 30,
          "headers": {
            "Accept": "application/json"
          },
          "jsonPath": "$.${target}",
          "enableJsonPath": true
        }
